[project]
name = "add-project-name-here"
version = "0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "bblocks>=1.4.2",
    "oda-data>=1.5.3",
    "pandas>=2.2.3",
    "pydeflate>=2.1.1",
]
